name: LocalChat
main: mohagames\localchat\Main
version: 1.0.0
api: 3.0.0
author: Mohagames205

commands:
  localchat:
    description: Main localchat command
  lc:
    description: Main localchat command

permissions:
  lc.cmd.toggle:
    description: Allows the player to use the localchat toggle command
  lc.cmd.setdistance:
    description: Allows the player to use the localchat setdistance command
